# ------------------------------------------------------------
# 進捗記録の設定定義
# ------------------------------------------------------------
progress_tracking_config:
  name: "進捗追跡設定"
  description: "進捗記録の3つの用途別設定"
  # 必要に応じて、このファイルを更新してください
  
  file_management:
    # 日別ファイル分割の有効/無効
    daily_file_splitting: true
    # ファイル命名パターン(書式と拡張子は人間の指示に従って決める)
    file_naming_pattern: "{project_name}_results_{YYYY-MM-DD}.tsv"
    # 古いファイルのアーカイブ
    suggest_archive_old_files: true
    # 保持するファイル数（最新のN個）
    max_files_to_keep: 30
    # JST日時形式の標準化
    datetime_format: "JST (UTC+9) - YYYY-MM-DDTHH:MM:SS+09:00"
    # 時系列順序の重要性
    chronological_order: true

  # Records for SpreadSheet - スプレッドシート用の記録
  records_for_spreadsheet:
    format: "TSV"
    fields:
      - "DateTime"     # JST形式のタイムスタンプ（時系列順序用）
      - "ServiceName"  # サービス名
      - "Environment" # 環境
      - "Status"      # ステータス (PENDING/INPROGRESS/DONE/ERROR/BLOCKED/READY)
      - "DevPR"       # 開発PR
      - "ProdPR"      # 本番PR
      - "Notes"       # 詳細メモ・進捗・課題追跡
    template: "{DateTime}	{ServiceName}	{Environment}	{Status}	{DevPR}	{ProdPR}	{Notes}"
    example: "2025-09-11T16:32:28+09:00	example-service	development	INPROGRESS	https://github.com/org/repo/pull/12345		CI success, waiting for review"
    status_values:
      - "PENDING: 未開始"
      - "INPROGRESS: 作業中"
      - "DONE: 完了"
      - "ERROR: エラー発生"
      - "BLOCKED: ブロック中"
      - "READY: 準備完了"
  
  # Working result for AI agent own - AIエージェント自身の作業結果記録
  working_result_for_ai_agent_own:
    format: "CSV"
    fields:
      - "service"        # サービス名
      - "environment"    # 環境
      - "status"         # ステータス
      - "started_at"     # 開始時刻
      - "completed_at"   # 完了時刻
      - "duration"       # 所要時間
      - "issues"         # 発生した問題
      - "solutions"      # 適用した解決策
      - "next_steps"     # 次のステップ
      - "lessons_learned" # 学んだこと
    template: |
      Service,Environment,Status,Started At,Completed At,Duration,Issues,Solutions,Next Steps,Lessons Learned
      {service},{environment},{status},{started_at},{completed_at},{duration},"{issues}","{solutions}","{next_steps}","{lessons_learned}"
    example: |
      Service,Environment,Status,Started At,Completed At,Duration,Issues,Solutions,Next Steps,Lessons Learned
      example-service,development,INPROGRESS,2025-01-21 10:30:00,,,"Git branch conflict occurred","Deleted existing branch and created new one","Wait for CI completion; Post Slack notification","Always check existing branches before creating new ones"
  
  # Evidence Report for Issue Tracker - 課題管理ツール用のエビデンス報告
  evidence_report_for_issue_tracker:
    format: "Markdown"
    fields:
      - "service"        # サービス名
      - "environment"    # 環境
      - "operation"      # 作業内容
      - "status"         # 結果
      - "pr_url"         # PR URL
      - "ci_result"      # CI結果
      - "slack_status"   # Slack投稿状況
      - "start_time"     # 開始時刻
      - "end_time"       # 終了時刻
      - "duration"       # 所要時間
      - "notes"          # 特記事項
    template: |
      ## 作業完了報告
      
      ### 対象
      - **マイクロサービス**: {service}
      - **環境**: {environment}
      - **作業内容**: {operation}
      
      ### 実行結果
      - **ステータス**: {status}
      - **PR URL**: {pr_url}
      - **CI結果**: {ci_result}
      - **Slack投稿**: {slack_status}
      
      ### 実行時間
      - **開始時刻**: {start_time}
      - **完了時刻**: {end_time}
      - **所要時間**: {duration}
      
      ### 特記事項
      {notes}
    example: |
      ## 作業完了報告
      
      ### 対象
      - **マイクロサービス**: example-service
      - **環境**: development
      - **作業内容**: サービスのバージョンアップ
      
      ### 実行結果
      - **ステータス**: INPROGRESS
      - **PR URL**: https://github.com/your_org/your_repo/pull/12345
      - **CI結果**: CI success, waiting for review
      - **Slack投稿**: Sent
      
      ### 実行時間
      - **開始時刻**: 2025-01-21 10:30:00
      - **完了時刻**: 
      - **所要時間**: 
      
      ### 特記事項
      - Git branch conflict occurred and resolved
      - CI is currently running
      - Slack notification sent successfully
