# ------------------------------------------------------------
# Progress Tracking Configuration Definition
# ------------------------------------------------------------
progress_tracking_config:
  name: "Progress Tracking Configuration"
  description: "Three purpose-specific settings for progress recording"
  # Please update this file as needed
  
  file_management:
    # Enable/disable daily file splitting
    daily_file_splitting: true
    # File naming pattern (format and extension determined by human instructions)
    file_naming_pattern: "{YYYY-MM-DD}_work_log.*"
    # Archive old files
    suggest_archive_old_files: true
    # Number of files to keep (latest N files)
    max_files_to_keep: 30
    
    # 保存場所の明示
    base_directory: "progress_tracking/files/"
    directory_structure: "日付別ファイル管理"
    
    # 記録方法の明示
    recording_method: "write_tool_or_search_replace_tool"
    recording_timing: "1タスク完了時にレコード追加"
    
    # ファイル操作の具体例
    operation_examples:
      new_file: "write toolで新規作成"
      append_record: "search_replace toolで既存ファイルに追記"  
  # Working result for AI agent own - AI agent's own work result records
  working_result_for_ai_agent_own:
    format: "CSV"
    fields:
      - "service"          # Service name
      - "environment"      # Environment
      - "status"           # Status
      - "started_at"       # Start time
      - "completed_at"     # Completion time
      - "duration"         # Duration
      - "issues"           # Issues that occurred
      - "solutions"        # Applied solutions
      - "next_steps"       # Next steps
      - "lessons_learned"  # Lessons learned
    template: |
      Service,Environment,Status,Started At,Completed At,Duration,Issues,Solutions,Next Steps,Lessons Learned
      {service},{environment},{status},{started_at},{completed_at},{duration},"{issues}","{solutions}","{next_steps}","{lessons_learned}"
      {service},{environment},{status},{started_at},{completed_at},{duration},"{issues}","{solutions}","{next_steps}","{lessons_learned}"
    example: |
      Service,Environment,Status,Started At,Completed At,Duration,Issues,Solutions,Next Steps,Lessons Learned
      example-service,development,INPROGRESS,2025-01-21 10:30:00,,,"Git branch conflict occurred","Deleted existing branch and created new one","Wait for CI completion; Post Slack notification","Always check existing branches before creating new ones"

# AI Agent向けの具体的な実装ガイド
ai_agent_implementation_guide:
  step1: "タスク完了時に progress_tracking/files/{YYYY-MM-DD}_work_log.csv の存在確認"
  step2: "ファイルが存在しない場合はヘッダー付きで新規作成"
  step3: "ファイルが存在する場合は新しいレコードを追記"
  step4: "JST時刻でタイムスタンプを記録"
  
  implementation_example:
    new_file_creation: |
      write tool使用例:
      - file_path: "progress_tracking/files/2025-09-25_work_log.csv"
      - contents: ヘッダー行 + 最初のレコード
    
    record_append: |
      search_replace tool使用例:
      - old_string: 最後の行
      - new_string: 最後の行 + 改行 + 新しいレコード
    
    timing_format: "YYYY-MM-DDTHH:MM:SS+09:00 (JST)"
  