# やりたいオペレーション
- 概要：(例)terraformのモジュールのバージョンアップ
- タスク：
  - 対象の確認:
    - マイクロサービス名
    - 環境
    - モジュールの利用状況
    - モジュールのバージョン
  - 事前準備
    - 事前連絡
      - Slackでの連絡
    - ツールの準備
      - ツールのダウンロード
      - 基本設定
      - 環境変数
    - 開始記録
  - バージョンアップ作業
    - ツールによる更新
    - AIによるファイル修正
    - プルリクエストの作成
  - レビュー依頼
    - Slackでの連絡
  - マージ後作業
    - CI成功確認
      - 失敗時
        - トラブルシューティング
        - リカバリ作業実施連絡
  - 記録更新作業
    - Slackでの連絡
    - AI保持管理記録の更新
    - チケットシステムへの投稿
    - その他