- グローバル変数:
  - repo_root: /Users/foobar/repos
  - logging_config: "activity_log/activity_log_config.yaml"
  - environment_config: "environment/system_environment.yaml"

# やりたいオペレーション
- 概要:(例)terraformのモジュールのバージョンアップ
- タスク:
  - 対象の確認:
    - マイクロサービス名
    - 環境
    - モジュールの利用状況
    - モジュールのバージョン
  - 事前準備
    - lesson_learned_check: "類似作業の過去の学習内容を確認（philosophy/lesson_learned.yaml）"
    - 事前連絡
      - Slackでの連絡
    - ツールの準備
      - ツールのダウンロード
      - 基本設定
      - 環境変数
    - 開始記録
  - バージョンアップ作業
    - pre_task_lesson_check: "作業開始前に関連する過去のトラブル事例を確認"
    - ツールによる更新
    - AIによるファイル修正
    - プルリクエストの作成
  - レビュー依頼
    - Slackでの連絡
  - マージ後作業
    - CI成功確認
      - 失敗時
        - トラブルシューティング
        - リカバリ作業実施連絡
  - 記録更新作業
    - Slackでの連絡
    - AI保持管理記録の更新
    - lesson_learned_update: "今回の作業で新たに学んだことがあればlesson_learnedに追加"
    - チケットシステムへの投稿
    - その他