# Global Variables:
  - repo_root: /Users/tearthesky/work/repo

- Task: "Create spanner-kit version upgrade PR"
  - Work: Execute {repo_root}/merpay-sre-scripts/spanner/spanner-kit-version-updater/create_pr_080.sh
  - Preparation
    - Check current date and time
    - Check required script arguments
    - Check version upgrade necessity
      - Check if target microservice has spanner-kit definition file in target environment
        - {repo_root}/microservices-terraform/terraform/microservices/{microservice_name}/{environment}/module_microservice_spanner_kit.tf
      - Check if module version is below 0.8.0
        - If below 0.8.0: Version upgrade required
        - If 0.8.0 or above: Version upgrade not required
  - Record results
    - Add log according to activity_log/activity_log_config.yaml

- Subtask: "Post spanner-kit version upgrade PR review request"
  - Work: Execute only the Slack posting part of {repo_root}/merpay-sre-scripts/spanner/spanner-kit-version-updater/create_pr_080.sh
  - Preparation
    - Check current date and time
    - Check required script arguments
    - Check created PR
  - Important notes
    - Use review request text exactly as is, without any modifications
  - Record results
    - Add log according to activity_log/activity_log_config.yaml

- Subtask: "Delete unnecessary resources"
  - Work: Execute {repo_root}/merpay-sre-scripts/spanner/spanner-kit-version-updater/delete_unused_resources.sh
  - Preparation
    - Check current date and time
    - Check required script arguments
    - Check unnecessary resources
      - Check unnecessary resources
  - Record results
    - Add log according to activity_log/activity_log_config.yaml
