# Desired Operation
- Overview: (Example) Terraform module version upgrade
- Tasks:
  - Target Confirmation:
    - Microservice name
    - Environment
    - Module usage status
    - Module version
  - Preparation
    - lesson_learned_check: "Check past learning content from similar work (philosophy/lesson_learned.yaml)"
    - Pre-communication
      - Slack notification
    - Tool preparation
      - Tool download
      - Basic configuration
      - Environment variables
    - Start recording
  - Version upgrade work
    - pre_task_lesson_check: "Check related past trouble cases before starting work"
    - Tool-based updates
    - AI file modifications
    - Pull request creation
  - Review request
    - Slack notification
  - Post-merge work
    - CI success confirmation
      - On failure
        - Troubleshooting
        - Recovery work notification
  - Record update work
    - Slack notification
    - AI management record updates
    - lesson_learned_update: "Add to lesson_learned if there are new learnings from this work"
    - Issue tracker posting
    - Others
